id: gcp_taxi_scheduled
namespace: taxi.etl

inputs:
  - name: taxi
    type: STRING
    defaults: green
  - name: year
    type: STRING
  - name: month
    type: STRING

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{inputs.taxi}}/{{inputs.taxi}}_tripdata_{{inputs.year}}-{{inputs.month}}.csv"
    output: "{{inputs.taxi}}_tripdata_{{inputs.year}}-{{inputs.month}}.csv"

  - id: convert_to_parquet
    type: io.kestra.plugin.serdes.csv.CsvToParquet
    from: "{{outputs.extract.output}}"
    timeZone: UTC

  - id: upload_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{outputs.convert_to_parquet.uri}}"
    to: "gs://bucket-name/{{inputs.taxi}}/{{inputs.year}}/{{inputs.taxi}}_tripdata_{{inputs.year}}-{{inputs.month}}.parquet"
    serviceAccount: "{{secret('GCP_SA_CREDENTIALS')}}"

  - id: bq_load
    type: io.kestra.plugin.gcp.bigquery.Load
    from: "{{outputs.convert_to_parquet.uri}}"
    destinationTable: "dataset.{{inputs.taxi}}_trips"
    format: PARQUET
    serviceAccount: "{{secret('GCP_SA_CREDENTIALS')}}"
    writeDisposition: WRITE_APPEND

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *"
    backfill:
      start: 2021-01-01
      end: 2021-07-31
    inputs:
      taxi: green
      year: "{{trigger.date.year}}"
      month: "{{trigger.date.month}}"